# First ML Project with MLFlow

#### Importing Libraries

In [18]:
import pandas as pd
import numpy as np
import mlflow
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from mlflow.models import infer_signature
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, precision_score, recall_score

#### Loading Dataset from Sklearn Module

In [5]:
## Loading dataset

X, y = datasets.load_iris(return_X_y= True)

In [7]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#### Splitting Data into Training and Testing Sets

In [10]:
# Splitting dataset

X_train, X_test, y_train,y_test = train_test_split(X,y, test_size=0.2, shuffle = True,random_state=142)

#### Choosing a Specigic Set of Parameters for Model Training

In [13]:
# Defining model parameters

params = {"penalty":"l2","solver":"lbfgs","max_iter": 1000, "multi_class": "auto", "random_state": 123}

#### Initializing the Logistic Regression Model with our dict of parameters, and training it

In [14]:
# Train Model

lr = LogisticRegression(**params)

lr.fit(X_train,y_train)

c:\Users\psalm\Downloads\MLops\MlFlow\mlflow\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=123)

#### Making Predictions on our Test Set

In [15]:
# Prediciton 

y_pred = lr.predict(X_test)
y_pred

array([0, 1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 0, 2, 1, 1, 2, 2, 1,
       0, 1, 2, 2, 2, 2, 0, 1])

#### Calculating the Accuracy of the Trained Model

In [19]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9333333333333333

#### Calculating the Confusion Matrix

In [22]:
cm = confusion_matrix(y_pred,y_test)
cm

array([[ 7,  0,  0],
       [ 0, 12,  1],
       [ 0,  1,  9]])

#### Calculating the Classification Report

In [24]:
cr = classification_report(y_pred,y_test)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.92      0.92      0.92        13
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



#### Setting the location (local host) for logging and retrieving experiment data

##### Purpose: This ensures all experiment data is stored in one centralized location

##### How Often We Use this: This step is always needed, when we want to track experiments with MLFlow

In [ ]:
## Let's keep track of our approach using ML Flow

"""
 This url is your local host adress, just copy and paste it in the browser, and dont forget to first initialize the MLFlow Ui from the command prompt.
 - Open Command Prompt
 - Go to Your Working Directory (cd [location])
 - Type in "mlflo ui"
 - Here you go, the tracking server is iniliazed!
"""

mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000")  

In [ ]:
## Creating new MLflow experiment 
"""
What it does: Creates or sets the active experiment in MLFlow.
Why use it: Organizes runs under a named experiment for better management.
How often used: Always, to ensure runs are categorized.

"""

mlflow.set_experiment("1st Project with MLFLOW Tracking")

"""
## mlflow.start_run()

- What it does: Starts a new experiment run.
- Why use it: Groups all logs (parameters, metrics, artifacts) for a specific experiment execution.
- How often used: Always, for each unique experiment run.

"""
with mlflow.start_run():
    ## logging parameters
    mlflow.log_params(params)
    ## logging metrics
    mlflow.log_metric("Accuracy",accuracy)

    ## Setting tag to ensure we remember what we did and why!

    mlflow.set_tag("Training info", "1st LR model for Iris Dataset")

    ## Infer the model signature
    ## The schema of both input and output will be fixed, meaning that it ensures the model accepts and produces predictions in the correct format during deployment.

    signature = infer_signature(X_train, lr.predict(X_test))

    ## Logging the model
    ## Since we have used sklearn for training and validating the model,therefore we'll use mlflow.sklearn module to log the model
    ## It saves the trained model and its meta data to the tracking server

    model_info = mlflow.sklearn.log_model(
        sk_model = lr,
        artifact_path = "Iris_model",
        signature = signature,
        input_example = X_train,
        registered_model_name = "Tracking-First-ever-model"
    )

Successfully registered model 'Tracking-First-ever-model'.
2024/11/20 09:14:12 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Tracking-First-ever-model, version 1


🏃 View run bright-mole-969 at: http://127.0.0.1:5000/#/experiments/621368122053747939/runs/25aa547b06254bf88267831c66eddeae
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/621368122053747939


Created version '1' of model 'Tracking-First-ever-model'.


### Tracking another experiment to observe the changes in the tracking server and its ui

In [ ]:
# Defining model parameters

params = {"penalty":"l2","solver":"lbfgs","max_iter": 1000, "multi_class": "auto", "random_state": 123}

In [ ]:
# Train Model

lr = LogisticRegression(**params)

lr.fit(X_train,y_train)

c:\Users\psalm\Downloads\MLops\MlFlow\mlflow\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=123)

In [ ]:
# Prediciton 

y_pred = lr.predict(X_test)
y_pred

array([0, 1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 0, 2, 1, 1, 2, 2, 1,
       0, 1, 2, 2, 2, 2, 0, 1])

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9333333333333333

In [ ]:
cm = confusion_matrix(y_pred,y_test)
cm

array([[ 7,  0,  0],
       [ 0, 12,  1],
       [ 0,  1,  9]])

In [ ]:
cr = classification_report(y_pred,y_test)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.92      0.92      0.92        13
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



In [ ]:
## Let's keep track of our approach using ML Flow

mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000")

In [ ]:
## Creating new MLflow experiment 

mlflow.set_experiment("1st Project with MLFLOW Tracking")


with mlflow.start_run():
    ## logging parameters
    mlflow.log_params(params)
    ## logging metrics
    mlflow.log_metric("Accuracy",accuracy)

    ## Setting tag to remind what this run was for

    mlflow.set_tag("Training info", "1st LR model for Iris Dataset")

    ## Infer the model signature
    ## The schema of both input and output will be fixed

    signature = infer_signature(X_train, lr.predict(X_test))

    ## Logging the model
    ## Since we have used sklearn for training and validating the model,therefore we'll use mlflow.sklearn module to log the model

    model_info = mlflow.sklearn.log_model(
        sk_model = lr,                                          # The trained sklearn model that we want to log (which is logistic regression (lr))
        artifact_path = "Iris_model",                           # The relative path where the model will be stored as an artifact
        signature = signature,                                  # Model input and output structure
        input_example = X_train,                                # Example input data that demonstrates what kind of data model expects 
        registered_model_name = "Tracking-First-ever-model"     # A name for the model in the model registery, if a model is regisered it means its ready for production
    )

Successfully registered model 'Tracking-First-ever-model'.
2024/11/20 09:14:12 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Tracking-First-ever-model, version 1


🏃 View run bright-mole-969 at: http://127.0.0.1:5000/#/experiments/621368122053747939/runs/25aa547b06254bf88267831c66eddeae
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/621368122053747939


Created version '1' of model 'Tracking-First-ever-model'.


### 2nd Experiment with different parameters

In [29]:
# Defining model parameters

params = {"solver":"newton-cg","max_iter": 1500, "multi_class": "auto", "random_state": 321}
# Train Model

lr = LogisticRegression(**params)

lr.fit(X_train,y_train)
# Prediciton 

y_pred = lr.predict(X_test)
print(y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)
cm = confusion_matrix(y_pred,y_test)
print(cm)
cr = classification_report(y_pred,y_test)
print(cr)
## Let's keep track of our approach using ML Flow

mlflow.set_experiment("2nd Project with MLFLOW Tracking")


with mlflow.start_run():
    ## logging parameters
    mlflow.log_params(params)
    ## logging metrics
    mlflow.log_metric("Accuracy",accuracy)

    ## Setting tag to remind what this run was for

    mlflow.set_tag("Training info", "2nd LR model for Iris Dataset")

    ## Infer the model signature
    ## The schema of both input and output will be fixed

    signature = infer_signature(X_train, lr.predict(X_test))

    ## Logging the model
    ## Since we have used sklearn for training and validating the model,therefore we'll use mlflow.sklearn module to log the model

    model_info = mlflow.sklearn.log_model(
        sk_model = lr,
        artifact_path = "Iris_model",
        signature = signature,
        input_example = X_train,
        registered_model_name = "Tracking-Second-model"
    )


c:\Users\psalm\Downloads\MLops\MlFlow\mlflow\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
2024/11/20 09:23:52 INFO mlflow.tracking.fluent: Experiment with name '2nd Project with MLFLOW Tracking' does not exist. Creating a new experiment.


[0 1 1 2 1 1 0 0 2 1 1 1 2 0 1 0 2 1 1 2 2 1 0 1 2 2 2 2 0 1]
0.9333333333333333
[[ 7  0  0]
 [ 0 12  1]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.92      0.92      0.92        13
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



Successfully registered model 'Tracking-Second-model'.
2024/11/20 09:23:58 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Tracking-Second-model, version 1


🏃 View run bold-asp-400 at: http://127.0.0.1:5000/#/experiments/605624553166471182/runs/8d77a3c9663042cb89e261f7ca7c2439
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/605624553166471182


Created version '1' of model 'Tracking-Second-model'.


### Model Inferencing and Validating

#### Checking if the model is performing well on the test data

#### The following code is taken from: 
    *
    **- Go the MLFlow Ui**
    *- Click on the experiemnts section*
    *- Choose the desired experiment*
    *- From there go the aritifacts section*
    *- On the left hand side, you'll see a code under the section "Validate the model before deployment"*
    *- Copy the code and paste it in your notebook (like below) and run*

In [30]:
from mlflow.models import validate_serving_input

model_uri = 'runs:/25aa547b06254bf88267831c66eddeae/Iris_model'

# The model is logged with an input example. MLflow converts
# it into the serving payload format for the deployed model endpoint,
# and saves it to 'serving_input_payload.json'
serving_payload = """{
  "inputs": [
    [
      7.2,
      3.0,
      5.8,
      1.6
    ],
    [
      6.6,
      2.9,
      4.6,
      1.3
    ],
    [
      6.8,
      3.0,
      5.5,
      2.1
    ],
    [
      6.2,
      2.2,
      4.5,
      1.5
    ],
    [
      5.9,
      3.2,
      4.8,
      1.8
    ],
    [
      6.4,
      2.7,
      5.3,
      1.9
    ],
    [
      6.8,
      2.8,
      4.8,
      1.4
    ],
    [
      5.8,
      2.7,
      5.1,
      1.9
    ],
    [
      5.8,
      2.7,
      4.1,
      1.0
    ],
    [
      6.0,
      2.2,
      4.0,
      1.0
    ],
    [
      5.8,
      2.6,
      4.0,
      1.2
    ],
    [
      5.5,
      2.6,
      4.4,
      1.2
    ],
    [
      4.6,
      3.2,
      1.4,
      0.2
    ],
    [
      7.9,
      3.8,
      6.4,
      2.0
    ],
    [
      5.5,
      2.3,
      4.0,
      1.3
    ],
    [
      5.1,
      3.8,
      1.6,
      0.2
    ],
    [
      4.6,
      3.4,
      1.4,
      0.3
    ],
    [
      5.4,
      3.4,
      1.7,
      0.2
    ],
    [
      5.4,
      3.7,
      1.5,
      0.2
    ],
    [
      5.0,
      3.0,
      1.6,
      0.2
    ],
    [
      7.6,
      3.0,
      6.6,
      2.1
    ],
    [
      5.5,
      2.5,
      4.0,
      1.3
    ],
    [
      4.8,
      3.4,
      1.6,
      0.2
    ],
    [
      6.9,
      3.1,
      4.9,
      1.5
    ],
    [
      6.1,
      3.0,
      4.9,
      1.8
    ],
    [
      6.4,
      3.1,
      5.5,
      1.8
    ],
    [
      6.3,
      2.7,
      4.9,
      1.8
    ],
    [
      5.5,
      4.2,
      1.4,
      0.2
    ],
    [
      6.0,
      3.4,
      4.5,
      1.6
    ],
    [
      5.2,
      4.1,
      1.5,
      0.1
    ],
    [
      5.0,
      3.2,
      1.2,
      0.2
    ],
    [
      5.0,
      3.6,
      1.4,
      0.2
    ],
    [
      5.4,
      3.9,
      1.3,
      0.4
    ],
    [
      5.9,
      3.0,
      4.2,
      1.5
    ],
    [
      6.3,
      2.9,
      5.6,
      1.8
    ],
    [
      6.5,
      2.8,
      4.6,
      1.5
    ],
    [
      7.7,
      3.8,
      6.7,
      2.2
    ],
    [
      4.6,
      3.6,
      1.0,
      0.2
    ],
    [
      4.9,
      2.4,
      3.3,
      1.0
    ],
    [
      5.6,
      3.0,
      4.5,
      1.5
    ],
    [
      4.8,
      3.1,
      1.6,
      0.2
    ],
    [
      7.3,
      2.9,
      6.3,
      1.8
    ],
    [
      6.5,
      3.2,
      5.1,
      2.0
    ],
    [
      5.8,
      4.0,
      1.2,
      0.2
    ],
    [
      5.7,
      2.5,
      5.0,
      2.0
    ],
    [
      5.2,
      3.4,
      1.4,
      0.2
    ],
    [
      4.5,
      2.3,
      1.3,
      0.3
    ],
    [
      6.3,
      2.5,
      5.0,
      1.9
    ],
    [
      6.4,
      2.8,
      5.6,
      2.1
    ],
    [
      4.8,
      3.4,
      1.9,
      0.2
    ],
    [
      6.7,
      3.3,
      5.7,
      2.1
    ],
    [
      6.0,
      3.0,
      4.8,
      1.8
    ],
    [
      4.8,
      3.0,
      1.4,
      0.3
    ],
    [
      5.4,
      3.9,
      1.7,
      0.4
    ],
    [
      6.7,
      3.0,
      5.2,
      2.3
    ],
    [
      6.5,
      3.0,
      5.2,
      2.0
    ],
    [
      5.6,
      2.8,
      4.9,
      2.0
    ],
    [
      6.0,
      2.7,
      5.1,
      1.6
    ],
    [
      7.2,
      3.2,
      6.0,
      1.8
    ],
    [
      6.3,
      3.4,
      5.6,
      2.4
    ],
    [
      5.2,
      2.7,
      3.9,
      1.4
    ],
    [
      6.4,
      2.8,
      5.6,
      2.2
    ],
    [
      5.2,
      3.5,
      1.5,
      0.2
    ],
    [
      5.4,
      3.0,
      4.5,
      1.5
    ],
    [
      6.2,
      3.4,
      5.4,
      2.3
    ],
    [
      5.1,
      3.5,
      1.4,
      0.3
    ],
    [
      5.1,
      3.8,
      1.9,
      0.4
    ],
    [
      5.7,
      3.8,
      1.7,
      0.3
    ],
    [
      5.1,
      3.8,
      1.5,
      0.3
    ],
    [
      6.4,
      2.9,
      4.3,
      1.3
    ],
    [
      6.1,
      3.0,
      4.6,
      1.4
    ],
    [
      6.7,
      2.5,
      5.8,
      1.8
    ],
    [
      5.7,
      2.6,
      3.5,
      1.0
    ],
    [
      5.0,
      3.5,
      1.3,
      0.3
    ],
    [
      7.1,
      3.0,
      5.9,
      2.1
    ],
    [
      6.4,
      3.2,
      4.5,
      1.5
    ],
    [
      4.3,
      3.0,
      1.1,
      0.1
    ],
    [
      6.1,
      2.6,
      5.6,
      1.4
    ],
    [
      4.7,
      3.2,
      1.6,
      0.2
    ],
    [
      4.4,
      3.0,
      1.3,
      0.2
    ],
    [
      5.8,
      2.8,
      5.1,
      2.4
    ],
    [
      5.7,
      2.9,
      4.2,
      1.3
    ],
    [
      4.9,
      3.6,
      1.4,
      0.1
    ],
    [
      5.0,
      2.3,
      3.3,
      1.0
    ],
    [
      5.5,
      3.5,
      1.3,
      0.2
    ],
    [
      5.5,
      2.4,
      3.7,
      1.0
    ],
    [
      6.5,
      3.0,
      5.8,
      2.2
    ],
    [
      6.3,
      3.3,
      6.0,
      2.5
    ],
    [
      6.0,
      2.2,
      5.0,
      1.5
    ],
    [
      5.6,
      3.0,
      4.1,
      1.3
    ],
    [
      4.7,
      3.2,
      1.3,
      0.2
    ],
    [
      6.2,
      2.9,
      4.3,
      1.3
    ],
    [
      4.9,
      3.0,
      1.4,
      0.2
    ],
    [
      5.7,
      4.4,
      1.5,
      0.4
    ],
    [
      6.7,
      3.1,
      4.7,
      1.5
    ],
    [
      5.1,
      3.3,
      1.7,
      0.5
    ],
    [
      4.4,
      2.9,
      1.4,
      0.2
    ],
    [
      6.7,
      3.3,
      5.7,
      2.5
    ],
    [
      6.4,
      3.2,
      5.3,
      2.3
    ],
    [
      4.9,
      3.1,
      1.5,
      0.1
    ],
    [
      7.7,
      2.6,
      6.9,
      2.3
    ],
    [
      5.8,
      2.7,
      3.9,
      1.2
    ],
    [
      6.9,
      3.2,
      5.7,
      2.3
    ],
    [
      6.6,
      3.0,
      4.4,
      1.4
    ],
    [
      5.7,
      2.8,
      4.5,
      1.3
    ],
    [
      6.1,
      2.9,
      4.7,
      1.4
    ],
    [
      5.6,
      2.7,
      4.2,
      1.3
    ],
    [
      5.4,
      3.4,
      1.5,
      0.4
    ],
    [
      7.0,
      3.2,
      4.7,
      1.4
    ],
    [
      6.3,
      2.3,
      4.4,
      1.3
    ],
    [
      6.5,
      3.0,
      5.5,
      1.8
    ],
    [
      6.9,
      3.1,
      5.4,
      2.1
    ],
    [
      6.7,
      3.1,
      5.6,
      2.4
    ],
    [
      4.9,
      3.1,
      1.5,
      0.2
    ],
    [
      6.9,
      3.1,
      5.1,
      2.3
    ],
    [
      5.0,
      3.3,
      1.4,
      0.2
    ],
    [
      5.5,
      2.4,
      3.8,
      1.1
    ],
    [
      5.0,
      3.4,
      1.6,
      0.4
    ],
    [
      4.8,
      3.0,
      1.4,
      0.1
    ],
    [
      5.1,
      3.7,
      1.5,
      0.4
    ]
  ]
}"""

# Validate the serving payload works on the model
validate_serving_input(model_uri, serving_payload)

array([2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 2, 1,
       0, 1, 2, 2, 2, 0, 1, 0, 0, 0, 0, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 0,
       2, 0, 0, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2, 0,
       0, 0, 0, 1, 1, 2, 1, 0, 2, 1, 0, 2, 0, 0, 2, 1, 0, 1, 0, 1, 2, 2,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 2, 2, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1,
       2, 2, 2, 0, 2, 0, 1, 0, 0, 0])

### Loading the model as a python function

In [32]:
## mlflow.pyfunc is the function used to load the trained model

loaded_model = mlflow.pyfunc.load_model(model_info.model_uri)

In [33]:
predi = loaded_model.predict(X_test)
print(predi)

[0 1 1 2 1 1 0 0 2 1 1 1 2 0 1 0 2 1 1 2 2 1 0 1 2 2 2 2 0 1]


In [34]:
feature_name = datasets.load_iris().feature_names
feature_name

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [36]:
## Displaying results as DataFrame
results = pd.DataFrame(X_test, columns = feature_name)
results["actual class"] = y_test
results['Predictions'] = predi



In [37]:
results

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 4.6               3.1                1.5               0.2   
1                 6.7               3.1                4.4               1.4   
2                 6.3               3.3                4.7               1.6   
3                 7.7               2.8                6.7               2.0   
4                 5.7               2.8                4.1               1.3   
5                 6.1               2.8                4.7               1.2   
6                 5.3               3.7                1.5               0.2   
7                 5.1               3.4                1.5               0.2   
8                 6.2               2.8                4.8               1.8   
9                 6.1               2.8                4.0               1.3   
10                5.6               2.9                3.6               1.3   
11                5.7               3.0                4.2               1.2   
12                6.8               3.2                5.9               2.3   
13                5.1               3.5                1.4               0.2   
14                6.3               2.5                4.9               1.5   
15                4.4               3.2                1.3               0.2   
16                7.4               2.8                6.1               1.9   
17                5.0               2.0                3.5               1.0   
18                4.9               2.5                4.5               1.7   
19                6.7               3.0                5.0               1.7   
20                5.8               2.7                5.1               1.9   
21                5.6               2.5                3.9               1.1   
22                5.0               3.5                1.6               0.6   
23                5.1               2.5                3.0               1.1   
24                7.7               3.0                6.1               2.3   
25                6.3               2.8                5.1               1.5   
26                7.2               3.6                6.1               2.5   
27                5.9               3.0                5.1               1.8   
28                5.0               3.4                1.5               0.2   
29                6.0               2.9                4.5               1.5   

    actual class  Predictions  
0              0            0  
1              1            1  
2              1            1  
3              2            2  
4              1            1  
5              1            1  
6              0            0  
7              0            0  
8              2            2  
9              1            1  
10             1            1  
11             1            1  
12             2            2  
13             0            0  
14             1            1  
15             0            0  
16             2            2  
17             1            1  
18             2            1  
19             1            2  
20             2            2  
21             1            1  
22             0            0  
23             1            1  
24             2            2  
25             2            2  
26             2            2  
27             2            2  
28             0            0  
29             1            1

### Model Registery

In [39]:
# Model Registory is like a store house where we save all the versions of our trained models, keep track of experiments, resutls and scores. 
# It allows us to save tags,aliases, and other options to keep track of all our experiments

In [41]:
params = {"penalty": 'l1', 'max_iter': 500, 'n_jobs': -1, 'class_weight': 'balanced', 'solver':'saga', 'random_state':43, 'multi_class':'auto'}

In [42]:
lr = LogisticRegression(**params)
lr.fit(X_train,y_train)

c:\Users\psalm\Downloads\MLops\MlFlow\mlflow\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\psalm\Downloads\MLops\MlFlow\mlflow\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(class_weight='balanced', max_iter=500, multi_class='auto',
                   n_jobs=-1, penalty='l1', random_state=43, solver='saga')

In [43]:
predict = lr.predict(X_test)
predict

array([0, 1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 1, 0, 2, 1, 2, 1, 2, 1,
       0, 1, 2, 1, 2, 2, 0, 1])

In [44]:
acc = accuracy_score(predict, y_test)
acc

0.9666666666666667

In [54]:
f1 = f1_score(predict, y_test, average = 'weighted')
print(f1)

0.9669265756985055


In [56]:
precision = precision_score(predict, y_test,average = 'weighted')
print(precision)

0.9700000000000001


In [57]:
recall = recall_score(predict, y_test, average = 'weighted')
print(recall)

0.9666666666666667


In [59]:
mlflow.set_experiment("LR without Registory")

with mlflow.start_run():
    ## logging parameters

    mlflow.log_params(params)

    ## Logging Metrics

    mlflow.log_metric('Accuracy', acc)
    mlflow.log_metric('F1-Score',f1)
    mlflow.log_metric('Precision',precision)
    mlflow.log_metric('Recall', recall)

    ## Setting Tags

    mlflow.set_tag("Training Model Information","Best LR model for Iris Dataset")

    ## Infer Model Signature, This is used to showcase the schema of inputs and Outputs

    signature = infer_signature(X_train, lr.predict(X_test))

    ## Logging Model 

    model_info = mlflow.sklearn.log_model(
        sk_model = lr,
        artifact_path = "Iris_model",
        signature = signature,
        input_example = X_train
    )

🏃 View run likeable-lark-272 at: http://127.0.0.1:5000/#/experiments/152510223557962989/runs/be67e7454e9843289002d3b2a5961a91
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/152510223557962989
